config/routes.rb
Rails.application.routes.draw do
  root 'short_links#index'
  get  ':id' => 'short_links#redirect'
  get  'a/sign_in',to: 'sessions#new'
  get  'a/sign_up',to: 'users#new'
  delete 'a/sign_out', to: 'sessions#destroy'
  resources :users
  resources :short_links
  resources :sessions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/short_link.rb
class ShortLink < ApplicationRecord
  before_save :generate_unique_id
  has_many :tracks
  scope :public_link, -> {where link_type:"public_link"}
  scope :user_link, -> {where link_type:"user_link"}
  scope :check_exist_url, ->(url){self.public_link.where(url: url)}

  belongs_to :user, optional: true


  def total_count
    tracks.size
  end

  def url_filter_by_ip
    tracks.group(:ip_address).size.keys.length
  end

  def url_filter_by_user
    tracks.group(:user_id).size.keys.length
  end

  private

  def generate_unique_id
    self.unique_key = SecureRandom.hex(6)
  end

end

app/models/track.rb
class Track < ApplicationRecord
  belongs_to :short_link
  scope :get_30_day_ago, -> {where(created_at: 30.days.ago..Time.now)}

end

app/models/user.rb
class User < ApplicationRecord
  has_many :short_links
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user,:logged_in?


  def current_user
    current_user ||= User.find_by_id(session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def require_login
    unless logged_in?
      redirect_to login_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email:params[:user][:email])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end


end

app/controllers/short_links_controller.rb
class ShortLinksController < ApplicationController
  before_action :log_track, :only => [:redirect]

  def show
    @shortlink = ShortLink.find(params[:id])

  end

  def redirect
    redirect_to @shortlink.url
  end

  def create
    @shortlink = ShortLink.new (param_short_link)
    if @shortlink.link_type == "user_link"
      @shortlink.user_id = current_user.id
      if @shortlink.save()
        redirect_to short_link_path(id: @shortlink.id)
      else
        redirect_to root_path
      end
    elsif @shortlink.link_type == "public_link"
      url_exist=ShortLink.check_exist_url(@shortlink.url)
      if url_exist.empty?
        if @shortlink.save()
          redirect_to short_link_path(id: @shortlink.id)
        else
          redirect_to root_path
        end
      else
        redirect_to short_link_path(id: url_exist.first.id)
      end
    end
  end

  private


  def check_url
    params[:short_link][:url] = "http://#{params[:short_link][:url]}" unless params[:short_link][:url]=~/^https?:\/\//
  end

  def param_short_link
    check_url
    params.require(:short_link).permit(:url, :link_type)
  end

  def log_track
    @shortlink = ShortLink.find_by(unique_key: params[:id])
    unless request.location.nil?
      unless request.location.country.empty?
        @shortlink.tracks.create(ip_address: request.remote_ip, user_id: current_user.nil? ? nil : current_user.id, country: request.location.country)
      else
        @shortlink.tracks.create(ip_address: request.remote_ip, user_id: current_user.nil? ? nil : current_user.id)
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new

    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render 'new'
    end
  end
  private

  def user_params
    params.require(:user).permit(:username,:email,:password,:password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/short_links_helper.rb
module ShortLinksHelper
end

app/helpers/shortened_urls_helper.rb
module ShortenedUrlsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ShortenUrl
    = csrf_meta_tags
    = javascript_include_tag "https://www.gstatic.com/charts/loader.js"
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      .row
        %ul.nav.pull-right.navbar-nav

          -unless logged_in?
            %li.nav-item
              %a.nav-link.sign_up{:href => "#{a_sign_up_path}"} Sign Up
            %li.nav-item
              %a.nav-link.sign_in{:href => "#{a_sign_in_path}"} Sign In
          -else
            %li.nav-item
              %a.nav-link.sign_up{:href => "#"}=current_user.username
            %li.nav-item
              =link_to "Log out", a_sign_out_path, method: :delete,class: "nav-link sign_in"
      .row
        = yield

app/views/short_links/index.html.haml
.row
  .col-xs-8.col-xs-offset-2
    .jumbotron.jumbotron-fluid{:style => "background-color: #563d7c; color: #fff"}
      %h1.display-3.text-xs-center{:style => "text-align: center"} Create shorten link
      %p.lead.text-xs-center{:style => "color:#cdbfe3"}

=simple_form_for ShortLink.new do |f|
  .row
    .col-xs-8.col-xs-offset-2
      = f.input :url, label: "Create Short Link:"
      -if logged_in?
        = f.hidden_field  :link_type, value:"user_link"
      -else
        = f.hidden_field  :link_type, value:"public_link"
      .text-xs-center
        = f.button :submit, "Create", class: "btn btn-secondary btn-block"

app/views/short_links/show.html.haml
%b Short Link
%br
  %a{:href=>root_url+@shortlink.unique_key, :target=>"_blank"} Click here
%br
  %b Daily hits for the last 30 days
= line_chart @shortlink.tracks.get_30_day_ago.group_by_day(:created_at).count
%br
  %b Weekly hits for the last 4 weeks
= line_chart @shortlink.tracks.group_by_week(:created_at,last:4).count\
%br
  %b Country
= pie_chart @shortlink.tracks.group(:country).size
%table
  %tr
    %td
      %b Total hit
    %td=@shortlink.total_count
  %tr
    %td
      %b Ip hit
    %td=@shortlink.url_filter_by_ip
  %tr
    %td
      %b User hit
    %td=@shortlink.url_filter_by_user

app/views/users/new.html.haml
.row
  .col-xs-8.col-xs-offset-2
    .jumbotron.jumbotron-fluid{:style => "background-color: #563d7c; color: #fff"}
      %h1.display-3.text-xs-center Sign up
      %p.lead.text-xs-center{:style => "color:#cdbfe3"}

= simple_form_for @user do |f|
  .row
    .col-xs-8.col-xs-offset-2
      = f.input :username, label: "Name:"
      = f.input :email, label: "Email:"
      = f.input :password, label: "Password:"
      = f.input :password_confirmation, label: "Confirm:"
      .text-xs-center
        = f.button :submit, "Register", class: "btn btn-secondary btn-block"